config/routes.rb
Rails.application.routes.draw do

  resources :users do
    resources :devices
  end

  #For assigning ip_addresses to devices
  post '/users/:user_id/device/assign', to: 'devices#assign_ip_address'
  get '/users/:user_id/device/assign/:id', to: 'devices#assign_ip_address'

  # For authtentication of the application
  match '/account/login', to: 'accounts#login', via: [:get, :post]
  get '/account/logout', to: 'accounts#logout'
  match '/account/signup', to: 'accounts#signup', via: [:get, :post]

  #For Account Activation
  get '/account/activate/:id', to: 'accounts#activate'
  match '/account/resend_activation', to: 'accounts#resend_activation', via: [:get, :post]

  #For Password Reset
  get'account/password_reset', to: 'accounts#password_reset'
  match 'account/reset_notice', to: 'accounts#reset_notice', via: [:get, :post]
  match 'account/reset_approved/:auth_token', to: 'accounts#reset_approved', via: :all

  root 'pages#home'
  get 'about', to: 'pages#about'

end

app/models/device.rb
class Device < ApplicationRecord

  validates :name, presence: true, uniqueness: true

  has_many :ip_addresses, dependent: :destroy
  belongs_to :user

end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  
  before_action :authenticate_user!
  before_action :set_device, only: [:show, :edit, :update, :destroy]
  before_action :set_user

  layout "startup"

  # GET /users/:user_id/devices
  # GET /users/:user_id/devices.json
  def index
    @devices = @user.devices
  end

  def assign_ip_address
    case request.method
      when "GET"
        @device = Device.find(params[:id])
      when "POST"
        #save form params to db
        respond_to do |format|
          @device = Device.find_by_name(params[:name])
          if @device
            @ip_add = @device.ip_addresses.new(:ip_value => params[:ip_address])
            if @ip_add.save
              format.html { redirect_to user_device_path(@user, @device),
                            notice: "Ip Address is successfully assigned to the device #{@device.name}." }
            else
              format.html { render :assign_ip_address, :locals => {:device_name => @device.name} }
            end
          end
        end

    end
  end

  # GET /users/:user_id/devices/:1
  # GET /users/:user_id/devices/1.json
  def show
  end

  # GET /users/:user_id/devices/new
  def new
    @device = Device.new
  end

  # GET /users/:user_id/devices/1
  def edit
  end

  # POST /users/:user_id/devices
  # POST /users/:user_id/devices.json
  def create
    @device = @user.devices.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to user_devices_path(@user), notice: 'Device was successfully added.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/:user_id/devices/1
  # PATCH/PUT /users/:user_id/devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params) &&
        format.html { redirect_to user_devices_path(@user), notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/:user_id/devices/1
  # DELETE /users/:user_id/devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to user_devices_url, notice: 'Device was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

  def set_user
    @user = User.find(params[:user_id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
  def device_params
    params.require(:device).permit(:name)
  end

end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/assign_ip_address.html.erb
<%= form_tag("/users/#{@user.id}/device/assign", method: "post") do %>
    <p>
    <% if @ip_add && @ip_add.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@ip_add.errors.count, "error") %> prohibited this device from being saved:</h2>

          <ul>
            <% @ip_add.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    </p>
    <p>
    <%= label_tag(:name, "Enter Device Name:") %>
    <% if @device %>
      <%= text_field_tag(:name, @device.name, :readonly => true) %>
    <% else %>
      <%= text_field_tag(:name, device_name, :readonly => true) %>
    <% end %>
    </p>

    <p>
    <%= label_tag(:ip_address, "Enter IP Address:") %>
    <%= text_field_tag(:ip_address) %>
    </p>
    <p>
    <%= submit_tag("Assign") %>
    </p>
<% end %>

<%= link_to 'Back', user_devices_path %>

app/views/devices/edit.html.erb
<h1>Editing Device</h1>

<%= form_for(@device, url: "/users/#{@user.id}/devices/#{@device.id}", html: {method: "patch"}) do |f| %>
    <% if @device.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

          <ul>
            <% @device.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="actions">
      <%= f.submit "Change Device" %>
    </div>
<% end %>

<%= link_to 'Show', user_device_path(@user, @device) %>
<%= link_to 'Back', user_devices_path %>

app/views/devices/index.html.erb
<h3 id="greet">Welcome <%= @user.login %></h3>

<h1><%= @user.login %>'s Devices</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="4">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= device.name %></td>
        <td><%= link_to 'Assign', "/users/#{@user.id}/device/assign/#{device.id}"%>
        <td><%= link_to 'Show', user_device_path(@user, device) %></td>
        <td><%= link_to 'Edit', edit_user_device_path(@user, device) %></td>
        <td><%= link_to 'Destroy', user_device_path(@user, device),
          method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/devices/new.html.erb
<h1>New Device</h1>

<%= form_for(@device, url: "/users/#{@user.id}/devices") do |f| %>
    <% if @device.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

          <ul>
            <% @device.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="actions">
      <%= f.submit "Add Device", :id => "new-btn" %>
    </div>
<% end %>

<%= link_to 'Back', user_devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @device.name %> <br><br>
  <strong>IpAddress:</strong>
    
<%= select_tag :ip_value, options_from_collection_for_select(@device.ip_addresses, :ip_value, :ip_value) %>
</p>



<%= link_to 'Edit', edit_user_device_path(@user, @device) %>
<%= link_to 'Back', user_devices_path %>