config/routes.rb
Rails.application.routes.draw do

  resources :users do
    resources :devices
  end

  #For assigning ip_addresses to devices
  post '/users/:user_id/device/assign', to: 'devices#assign_ip_address'
  get '/users/:user_id/device/assign/:id', to: 'devices#assign_ip_address'

  # For authtentication of the application
  match '/account/login', to: 'accounts#login', via: [:get, :post]
  get '/account/logout', to: 'accounts#logout'
  match '/account/signup', to: 'accounts#signup', via: [:get, :post]

  #For Account Activation
  get '/account/activate/:id', to: 'accounts#activate'
  match '/account/resend_activation', to: 'accounts#resend_activation', via: [:get, :post]

  #For Password Reset
  get'account/password_reset', to: 'accounts#password_reset'
  match 'account/reset_notice', to: 'accounts#reset_notice', via: [:get, :post]
  match 'account/reset_approved/:auth_token', to: 'accounts#reset_approved', via: :all

  root 'pages#home'
  get 'about', to: 'pages#about'

end

app/views/pages/_slide.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= link_to image_tag('s2.jpg')%>
        <div class="carousel-caption">
        Gadgets are awsome!!
        </div>
    </div>
    <div class="item">
      <%= link_to image_tag('s3.jpg')%>
        <div class="carousel-caption">
        Superb!!
        </div>
    </div>
    <div class="item">
      <%= link_to image_tag('s1.jpg')%>
      <div class="carousel-caption">
        Fantanstic!!
      </div>
    </div>
    ...
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/pages/about.html.erb
<body class="<%= @about_page ? 'aboutpage' : ''%>">
<div class="container">
  <h1>This is the about page of our application</h1>
  <p>The Ip Device Blog is a web application used for keeping track of the user's devices and their corresponding ipaddresses.
     The user has to signup for creating an account and get his/her account activated and then they can start creating
     their own devices and assign ip addresses to those devices. Once the devices have been assigned the addresses,
     they can view or delete their individual devices as per their convenience.</p>

  <%= link_to 'Home', root_path, :id => "btn" %>
</div>
</body>

app/views/pages/home.html.erb
<body class="<%= @home_page ? 'homepage' : ''%>">
<h1><center><strong>Welcome to Device Blog</strong></center></h1>
<%= render 'slide' %>
<section class="text-center jumbotron table-bordered">
  <div class="container">
    <div class="row">
      <h1 class="display-3"><strong>DEVICE BLOG</strong></h1>
      <%= link_to 'Sign Up', account_signup_path, class: "btn btn-primary btn-lg gradient" %>
      <%= link_to 'Sign In', account_login_path, class: "btn btn-primary btn-lg gradient" %>
      <%= link_to 'About', about_path, class: "btn btn-primary btn-lg gradient" %>
      </p>
    </div>
  </div>
</section>
</body>