config/routes.rb
Rails.application.routes.draw do

  resources :users do
    resources :devices
  end

  #For assigning ip_addresses to devices
  post '/users/:user_id/device/assign', to: 'devices#assign_ip_address'
  get '/users/:user_id/device/assign/:id', to: 'devices#assign_ip_address'

  # For authtentication of the application
  match '/account/login', to: 'accounts#login', via: [:get, :post]
  get '/account/logout', to: 'accounts#logout'
  match '/account/signup', to: 'accounts#signup', via: [:get, :post]

  #For Account Activation
  get '/account/activate/:id', to: 'accounts#activate'
  match '/account/resend_activation', to: 'accounts#resend_activation', via: [:get, :post]

  #For Password Reset
  get'account/password_reset', to: 'accounts#password_reset'
  match 'account/reset_notice', to: 'accounts#reset_notice', via: [:get, :post]
  match 'account/reset_approved/:auth_token', to: 'accounts#reset_approved', via: :all

  root 'pages#home'
  get 'about', to: 'pages#about'

end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
      <small>
          Copyright &copy; <a href ="https://deviceip-blog.herokuapp.com/">The Device Ip blog</a>
          by <a href="https://github.com/sharathror162">Sharath Chandra</a>  & Nischal
      </small>
      <!--<nav>-->
          <!--<ul>-->
              <!--<li><%#= link_to "About", about_path %></li>-->
          <!--</ul>-->
      <!--</nav>-->
  </footer>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to "Device Blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li id="home-link"><%= link_to "Home", root_url %></li>
        <li id="devices-link"><%= link_to "Devices", user_devices_path(@user) %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "New", new_user_device_path(@user) %></li>

          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li id="logout-link"><a href="/account/logout">Logout</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewIpAlloc</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/layouts/startup.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login page</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navigation'%>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>