config/routes.rb
Rails.application.routes.draw do

  resources :users do
    resources :devices
  end

  #For assigning ip_addresses to devices
  post '/users/:user_id/device/assign', to: 'devices#assign_ip_address'
  get '/users/:user_id/device/assign/:id', to: 'devices#assign_ip_address'

  # For authtentication of the application
  match '/account/login', to: 'accounts#login', via: [:get, :post]
  get '/account/logout', to: 'accounts#logout'
  match '/account/signup', to: 'accounts#signup', via: [:get, :post]

  #For Account Activation
  get '/account/activate/:id', to: 'accounts#activate'
  match '/account/resend_activation', to: 'accounts#resend_activation', via: [:get, :post]

  #For Password Reset
  get'account/password_reset', to: 'accounts#password_reset'
  match 'account/reset_notice', to: 'accounts#reset_notice', via: [:get, :post]
  match 'account/reset_approved/:auth_token', to: 'accounts#reset_approved', via: :all

  root 'pages#home'
  get 'about', to: 'pages#about'

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  before_action :set_user, only: [:activate]
  before_action :check_token_expiration, only: [:reset_approved]

  def signup
    case request.method
      when "GET"
      	@user = User.new
      when "POST"
        respond_to do |format|
      	  @user = User.new(user_params)
          unless User.find_by_email(@user.email).present?
            if @user.save
              EmailSenderJob.perform_later(@user)
              flash[:notice] = "Your account has been Successfully created and an activation link has been sent to
                                 your email #{@user.email}. Please check your inbox to activate your account."
              format.html { redirect_to account_login_path }
            else
              format.html { render :signup }
            end
          else
            flash.now[:notice] = "This Email #{@user.email} has already been taken. Please enter a new email"
            format.html { render :signup }
          end
      	end
    end
  end

  def password_reset
  end 

  def reset_notice
    case request.method
      when "POST"
      respond_to do |format|
        @user = User.find_by_email(params[:email])
        if params[:email].blank?
          flash.now[:notice] = 'Email Field Cannot Be Empty.'
          format.html { render :password_reset }
        elsif @user.nil?
          flash[:notice] = 'Sorry. Email does not exist. It may be because you do not have an account with us yet.
                            Please sign up now.'
          format.html { redirect_to account_login_path }
        elsif @user and @user.active?
          @user.send_password_reset
          flash[:notice] = "A Reset link has been sent to your email #{@user.email}.
                            Please click on it to finish resetting your password. Thank you."
          format.html { redirect_to account_login_path }
        else
          flash[:resend] = 'Your account has not been activated yet. Please check your email inbox to look
                            for the activation link. If you have not received your activation link yet,
                            click on this link to'
          format.html { redirect_to account_login_path }
        end
      end
    end
  end

  def reset_approved
    case request.method
      when "POST"
        respond_to do |format|
          @user = User.find_by_auth_token(params[:auth_token])
          if @user.update_attributes(user_params)
            flash[:notice] = 'Your Password has been Successfully reset.'
            format.html { redirect_to account_login_path }
          else
            flash[:notice] = 'Something went wrong.Please reset your password again.'
            format.html { render :reset_approved }
          end
        end
    end
  end 

  def activate
    respond_to do |format|
      @user.update_attributes(:active => true) unless @user.active?
      flash[:notice] = 'Your Account has been activated. Please Log In.'
      format.html { redirect_to account_login_path }
    end
  end

  def resend_activation
    case request.method
      when "POST"
        respond_to do |format|
          @user = User.find_by_email(params[:email])
          EmailSenderJob.perform_later(@user)
          flash.now[:resend] = 'Account activation link has been resent. Please check your email inbox.
                                If you have not received it yet for some reason, click to'
          format.html { render :login}
        end
    end
  end

  def login
  	case request.method
  	  when "POST"
  	  	respond_to do |format|
  	  	  @user = User.find_by_login(params[:login])

  	  	  if authorized_user?(@user, params[:password]) && @user.active?
            if params[:remember_me]
              cookies.permanent[:user_id] = @user.id
            else
              cookies[:user_id] = @user.id
            end
  	  	  	format.html {  redirect_to user_devices_path(@user) }
          elsif authorized_user?(@user, params[:password]) && @user.active.nil?
            flash[:resend] = 'Your account has not been activated yet. Please check your email inbox to look
                              for the activation link. If you have not received your activation link yet,
                              click on this link to'
            format.html { redirect_to account_login_path }
  	  	  else
  	  	  	flash[:error] = 'Warning! Invalid Username/Password.'
            format.html { redirect_to account_login_path }
          end
        end
  	end
  end

  def logout
  	respond_to do |format|
  	  cookies.delete(:user_id)
  	  flash[:notice] = 'User Successfully Logged Out'
  	  format.html { redirect_to account_login_path }
  	end
  end

  private

  def user_params
  	params.require(:user).permit(:login, :email, :password, :password_confirmation)
  end

  def set_user 
    @user = User.find(params[:id])
  end

  def authorized_user?(user, pass)
    return true if user && user.authenticate(pass)
  end

  def check_token_expiration
    @user = User.find_by_auth_token(params[:auth_token])
    if @user.token_expired?
      flash[:notice] = 'Your Password Reset request has been expired.'
      redirect_to account_login_path
      return false
    else
      return true
    end
  end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/login.html.erb
<div class="login">
  <div class="error-msg">
    <% if flash[:error] %>
        <div class="alert alert-danger alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= flash[:error] %>
        </div>
    <% elsif flash[:notice] %>
        <div class="alert alert-success alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= flash[:notice] %>
        </div>
    <% elsif flash[:resend] %>
        <div class="alert alert-success alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= flash[:resend] %> <a class="alert-link">resend it</a>
          <div id="resend-link" class="txt-fld-group">
            <input type="text" id="txt-fld"/>
            <button id="btn2">Resend Activation Link</button>
          </div>
        </div>
    <% end %>
  </div>

  <h3><strong>Sign In</strong></h3>
  
<%= form_tag("/account/login", method: "post", id: "login-form") do %>
  <div class="imgcontainer">
    <%= image_tag "mountain_hill.jpg", :class => "avatar" %>
  </div>

  <div>
    <%= label_tag(:login, "Username") %>
    <input id="login-txt" type="text" name="login">
    <span id="f1" class="txt-field">Username is empty</span>

    <%= label_tag(:password, "Password") %>
    <input id="pwd-txt" type="password" name="password">
    <span id="f2" class="txt-field">Password is empty</span>

    <%= submit_tag("Sign In", :id => "btn", :name => "submit") %>
    <span id="rme"><%= check_box_tag(:remember_me)%> Remember Me</span>
  </div>
  <% end %>

    <span id="frgt"><%= link_to 'Forgot your password? ', account_password_reset_path %> </span>

  <footer id="footer">
    <li>Not a member yet?<%= link_to 'Sign up now', account_signup_path %></li>
    <li><%= link_to 'Back to Home Page', root_path %></li>
  </footer>

</div>

app/views/accounts/password_reset.html.erb
<div class = "pwd_reset">
<p id="notice"><%= notice %></p>

<h1>Reset your password</h1>

<%= form_tag("/account/reset_notice", method: "post") do %>
  <div>
    <%= label_tag(:email, "Please enter your email:") %>
    <%= text_field_tag(:email) %>
  </div>

  <div>
    <%= submit_tag("Reset Password", :id=>"btn", :class=>"Test", :name=>"submit") %>
  </div>
<% end %>

<%= link_to 'Back to Home Page',root_path %>
</div>

app/views/accounts/reset_approved.html.erb
<%= form_for @user, url: {action: "reset_approved"} do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :password, "Please Enter Your New Password" %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation, "Please Re-Enter Your New Password" %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit "Update Password", :id=>"btn" %>
  </div>
<% end %>

app/views/accounts/signup.html.erb
<%= form_for @user, url: {action: "signup"} do |f| %>
    <% if @user.errors.any? %>
       <div class="alert alert-success" role="alert">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this device from being saved:</h2>

        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% elsif flash[:notice] %>
        <div class="alert alert-danger alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
            <%= flash[:notice] %>
          </div>
    <% end %>

  <div class="field">
    <%= f.label :login, "Please Enter Your Username:" %>
    <%= f.text_field :login %>
  </div>

  <div class="field">
    <%= f.label :email, "Please Enter Your Email (only gmail domain):" %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password, "Please Enter Your Password:" %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation, "Please Re-Enter Your Password:" %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up", :id=>"btn" %>
  </div>
<% end %>

<%= link_to 'Back to Home Page',root_path %> |
<%= link_to 'Back to Login Page',account_login_path %>